services:
  - type: web
    name: u-paul-ai
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: MODEL_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CREATOR_EMAILS
        sync: false
      - key: DEBI_EMAILS
        sync: false
      - key: FRIEND_EMAILS
        sync: false
      - key: SECRET_KEY
        sync: false
